# Generated by Django 5.0.2 on 2024-02-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_img', models.TextField()),
                ('title', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
