# Generated by Django 5.0.2 on 2024-02-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_content', '0004_alter_users_gender_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='users_photos/'),
        ),
    ]
