# Generated by Django 5.0.2 on 2024-02-29 17:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_content', '0006_animes_score_users_birthdate_alter_users_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animes',
            name='descriptionData',
            field=models.TextField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animes',
            name='descriptionEpisod',
            field=models.TextField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='identifier',
            field=models.CharField(default=uuid.uuid4, max_length=32),
        ),
    ]
