# Generated by Django 5.0.2 on 2024-02-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_content', '0006_alter_users_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.CharField(choices=[('Мужской', 'Мужской'), ('Женский', 'Женский'), ('Другой', 'Другой')], default='Другое', max_length=20),
        ),
    ]
