# Generated by Django 5.0.2 on 2024-03-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_content', '0007_remove_animes_description_animes_descriptiondata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manga_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manga_id', models.IntegerField()),
                ('Episodes', models.IntegerField()),
                ('Genres', models.TextField()),
                ('Themes', models.TextField()),
            ],
            options={
                'db_table': 'manga_info',
            },
        ),
        migrations.CreateModel(
            name='Mangas',
            fields=[
                ('manga_list_id', models.IntegerField(primary_key=True, serialize=False)),
                ('url_img', models.TextField()),
                ('title_ru', models.TextField()),
                ('title_en', models.TextField()),
                ('descriptionEpisod', models.TextField()),
                ('descriptionData', models.TextField()),
                ('score', models.FloatField()),
                ('studios', models.TextField()),
            ],
            options={
                'db_table': 'mangas',
            },
        ),
        migrations.CreateModel(
            name='Score_manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manga_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('score', models.IntegerField()),
                ('status', models.TextField(choices=[('completed', 'completed'), ('planned', 'planned'), ('dropped', 'dropped'), ('watching', 'watching')])),
                ('review', models.TextField()),
            ],
            options={
                'db_table': 'score_manga',
            },
        ),
    ]
