# Generated by Django 5.0.2 on 2024-02-27 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('get_content', '0005_users_photo'),
        ('get_content', '0007_alter_users_gender'),
    ]

    operations = [
    ]
