# Generated by Django 5.0.2 on 2024-02-27 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_content', '0008_merge_0005_users_photo_0007_alter_users_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='animes',
            name='score',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.CharField(choices=[('Мужской', 'Мужской'), ('Женский', 'Женский'), ('Другой', 'Другой')], default='Другое', max_length=20),
        ),
    ]
